package SyncService;


/**
* SyncService/SyncOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sync.idl
* Friday, 4 January 2013 3:12:40 PM EST
*/

public interface SyncOperations 
{
  int getOffset ();
} // interface SyncOperations
