package SyncService;


/**
* SyncService/Sync.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sync.idl
* Friday, 4 January 2013 3:12:39 PM EST
*/

public interface Sync extends SyncOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sync
