package SyncService;

/**
* SyncService/SyncHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sync.idl
* Friday, 4 January 2013 3:12:39 PM EST
*/

public final class SyncHolder implements org.omg.CORBA.portable.Streamable
{
  public SyncService.Sync value = null;

  public SyncHolder ()
  {
  }

  public SyncHolder (SyncService.Sync initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SyncService.SyncHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SyncService.SyncHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SyncService.SyncHelper.type ();
  }

}
